require("./klorofil-common")
require("../vendor/bootstrap/js/bootstrap.js")
require("../vendor/bootstrap/js/bootstrap.min.js")
require("../vendor/bootstrap/js/npm.js")
require("../vendor/chartist/js/chartist.js")
require("../vendor/chartist/js/chartist.min.js")
require("../vendor/jquery/jquery.js")
require("../vendor/jquery/jquery.min.js")
// require("../vendor/jquery/jquery.min.map")
// require("../vendor/jquery.easy-pie-chart/angular.easypiechart.js")
// require("../vendor/jquery.easy-pie-chart/angular.easypiechart.min.js")

require("../vendor/jquery.easy-pie-chart/easypiechart.js")
require("../vendor/jquery.easy-pie-chart/easypiechart.min.js")
require("../vendor/jquery.easy-pie-chart/jquery.easypiechart.js")
require("../vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js")
require("../vendor/jquery-slimscroll/jquery.slimscroll.js")
require("../vendor/jquery-slimscroll/jquery.slimscroll.min.js")
require("../vendor/toastr/toastr.min.js")
require("../vendor/toastr/toastr.js")